// Generated by wrangler types — placeholder until wrangler login
interface Env {
  DB: D1Database;
  ENVIRONMENT: string;
  IMX_API_SANDBOX: string;
  IMX_API_MAINNET: string;
  COLLECTION_CONTRACT_SANDBOX: string;
  COLLECTION_CONTRACT_MAINNET: string;
  INFURA_API_KEY: string;
}
